CREATE TABLE "HUBDADOS"."PBI_WORKSPACE"
(
    "ID_WORKSPACE" NUMBER GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1) NOT NULL ENABLE,
    "NOME" VARCHAR2(50) NOT NULL ENABLE,
    "DESCRICAO" VARCHAR2(255) NOT NULL ENABLE,
    "IMAGEM" VARCHAR2(255) NOT NULL ENABLE,
    "NR_SEQUENCIA" NUMBER NOT NULL ENABLE,
    "COR_HEX" VARCHAR2(7),
    CONSTRAINT "PBI_WORKSPACE_PK" PRIMARY KEY ("ID_WORKSPACE")
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "TS_DADOS";
